Repository SCP-SL-Plugin-YongAnTeam/YongAnFrame, pull requests merged in 2024-10, with the labels that each got.

#6 问题的修复
  Commands/PlayerCommand.cs
  Components/CapacityList.cs
  Players/FramePlayer.cs
  Players/HintManager.cs
  Roles/CustomRolePlus.cs
  YongAnFrame.csproj
  YongAnFrameConfig.cs
Labels: bug

#14 更新了自述文档
  README.md
Labels: documentation

#17 添加与完善经验系统
  Commands/ExpCommand.cs
  Commands/MessageCommand.cs
  Commands/PlayerCommand.cs
  Commands/SkillCommand.cs
  Components/CapacityList.cs
  Events/EventArgs/FramePlayer/FramePlayerInvalidingEventArgs.cs
  Events/Handlers/FramePlayer.cs
  Players/CustomPlayer.cs
  Players/FramePlayer.cs
  Players/HintManager.cs
  Players/ICustomAlgorithm.cs
  Properties/AssemblyInfo.cs
  README.md
  Roles/CustomRolePlus.cs
  Roles/Interfaces/ISkillActiveEnd.cs
  Roles/Interfaces/ISkillActiveStart.cs
  Roles/Interfaces/ISkillBurialEnd.cs
  Roles/MusicManager.cs
  Roles/SkillManager.cs
  YongAnFrame.csproj
  YongAnFrame.nuspec
  YongAnFrameConfig.cs
  packages.config
Labels: enhancement, help wanted, requires-testing

#19 doc
  Commands/ExpCommand.cs
  Players/CustomPlayer.cs
  Players/FramePlayer.cs
  Players/ICustomAlgorithm.cs
  Roles/Properties/SkillProperties.cs
  YongAnTool.cs
Labels: documentation
